#!/command/with-contenv bash
# shellcheck shell=bash

NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'

if [[ -s $LOG_LEVEL ]]; then
  printf >&2 "init: ${RED}Required Log Level parameter missing...\n${NC}"
  exit 1
fi
