---
name: Docker Build, Push and Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths-ignore:
      - .forgejo/**
      - .vscode/**
      - .gitignore
      - .yamllint
      - LICENSE
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker_version:
    name: Get Docker version from Dockerfile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read

    outputs:
      semver: ${{ steps.version.outputs.semver }}
      semver_minor: ${{ steps.version.outputs.semver_minor }}
      semver_major: ${{ steps.version.outputs.semver_major }}

    steps:
      - name: ⤵️ Checkout repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: Dockerfile

      - name: Get Docker version
        id: version
        shell: bash
        run: |
          VERSION=$(grep -i "^ARG ${NAME}_VERSION=" Dockerfile | cut -d= -f2)

          if [ -z "${VERSION}" ]; then
            echo "Could not retrieve version for $NAME"
            exit 1
          fi

          echo "Found $NAME version $VERSION"

          echo "semver=$VERSION" >> "$GITHUB_OUTPUT"
          echo "semver_minor=${VERSION%.*}" >> "$GITHUB_OUTPUT"
          echo "semver_major=${VERSION%.*.*}" >> "$GITHUB_OUTPUT"
        env:
          NAME: docker

  forgejo_runner_version:
    name: Get Forgejo Runner version from Dockerfile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read

    outputs:
      semver: ${{ steps.version.outputs.semver }}
      semver_minor: ${{ steps.version.outputs.semver_minor }}
      semver_major: ${{ steps.version.outputs.semver_major }}

    steps:
      - name: ⤵️ Checkout repository
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: Dockerfile

      - name: Get Forgejo Runner version
        id: version
        shell: bash
        run: |
          VERSION=$(grep -i "^ARG ${NAME}_VERSION=" Dockerfile | cut -d= -f2)

          if [ -z "${VERSION}" ]; then
            echo "Could not retrieve version for $NAME"
            exit 1
          fi

          echo "Found $NAME version $VERSION"

          echo "semver=$VERSION" >> "$GITHUB_OUTPUT"
          echo "semver_minor=${VERSION%.*}" >> "$GITHUB_OUTPUT"
          echo "semver_major=${VERSION%.*.*}" >> "$GITHUB_OUTPUT"
        env:
          NAME: forgejo_runner

  release:
    name: Release
    needs: [docker_version, forgejo_runner_version]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🚀 Create release
        # yamllint disable rule:line-length
        uses: akkuman/gitea-release-action@f66c1c98f12e032443e806fae4882a05368df40c # v1
        with:
          name: "v${{ needs.forgejo_runner_version.outputs.semver }} (dind ${{ needs.docker_version.outputs.semver }})"
          tag_name: "v${{ needs.forgejo_runner_version.outputs.semver }}-${{ needs.docker_version.outputs.semver }}"
        # yamllint enable rule:line-length

  build-and-push:
    name: Docker Build and Push Container to registries
    runs-on: ubuntu-latest
    needs: [docker_version, forgejo_runner_version, release]
    timeout-minutes: 30

    permissions:
      contents: read
      packages: write

    steps:
      - name: ⤵️ Checkout created tag
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🏗️ Setup qemu
        # yamllint disable-line rule:line-length
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: 🏗️ Set up Docker Buildx
        # yamllint disable-line rule:line-length
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: 🔑 Docker Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔑 Docker Login to GHCR Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 🔑 Docker Login to Local Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: 1d.lol
          username: ${{ vars.LOCAL_PACKAGES_USERNAME }}
          password: ${{ secrets.LOCAL_PACKAGES_TOKEN }}

      - name: 💄 Prepare Docker Metadata
        id: meta
        # yamllint disable rule:line-length
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/forgejo-runner-dind
            ghcr.io/${{ vars.GHCR_USERNAME }}/forgejo-runner-dind
            1d.lol/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver }}-dind-${{ needs.docker_version.outputs.semver }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver }}-dind-${{ needs.docker_version.outputs.semver_minor }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver }}-dind-${{ needs.docker_version.outputs.semver_major }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_minor }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_minor }}-dind-${{ needs.docker_version.outputs.semver }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_minor }}-dind-${{ needs.docker_version.outputs.semver_minor }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_minor }}-dind-${{ needs.docker_version.outputs.semver_major }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_major }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_major }}-dind-${{ needs.docker_version.outputs.semver }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_major }}-dind-${{ needs.docker_version.outputs.semver_minor }},enable={{is_default_branch}}
            type=raw,value=${{ needs.forgejo_runner_version.outputs.semver_major }}-dind-${{ needs.docker_version.outputs.semver_major }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Forgejo Runner With Docker
            org.opencontainers.image.description=Forgejo act runner with embedded Docker in Docker
            org.opencontainers.image.authors=Alex van den Hoogen
            org.opencontainers.image.documentation=https://github.com/alex3305/forgejo-runner-dind
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.source=https://github.com/alex3305/forgejo-runner-dind
            org.opencontainers.image.url=https://github.com/alex3305/forgejo-runner-dind
            org.opencontainers.image.vendor=Alex van den Hoogen
        # yamllint enable rule:line-length

      - name: 👷 Docker Build and push latest
        # yamllint disable-line rule:line-length
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
