---
name: Sync Labels to Forgejo

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - ".forgejo/labels.yaml"
      - ".forgejo/workflows/labels.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync labels
    runs-on: docker
    timeout-minutes: 2
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: .forgejo/labels.yaml

      - name: 🏷️ Run Label Sync
        # yamllint disable-line rule:line-length
        uses: https://git.ram.io/actions/action-label-sync@0906b5c8c8a610652f6057bb587cd36ec2ca399e # v1
        with:
          labels_file: .forgejo/labels.yaml
          delete_other_labels: true
