#!/usr/bin/env bash

HOSTNAME=$(hostname)

CONFIG_ARG=""
if [[ ! -z "${CONFIG_FILE}" ]]; then
  CONFIG_ARG="--config ${CONFIG_FILE}"
fi

EXTRA_ARGS=""
if [[ ! -z "${FORGEJO_RUNNER_LABELS}" ]]; then
  EXTRA_ARGS="${EXTRA_ARGS} --labels ${FORGEJO_RUNNER_LABELS}"
fi

cd /data

forgejo-runner register \
    --instance "${FORGEJO_INSTANCE_URL}" \
    --token    "${FORGEJO_REGISTRATION_TOKEN}" \
    --name     "${FORGEJO_RUNNER_NAME:-$HOSTNAME}" \
    ${CONFIG_ARG} ${EXTRA_ARGS} --no-interactive 2>&1 | tee /tmp/reg.log

cat /tmp/reg.log | grep 'Runner registered successfully' > /dev/null

if [[ $? -ne 0 ]]; then
  exit 6
fi

exit 0
