#!/command/with-contenv bash
# shellcheck shell=bash

CONFIG_ARG=""
if [[ ! -z "${CONFIG_FILE}" ]]; then
  CONFIG_ARG="--config ${CONFIG_FILE}"
fi

# Prevent reading the token from the forgejo-runner process
unset FORGEJO_REGISTRATION_TOKEN

cd /data
exec forgejo-runner daemon ${CONFIG_ARG}
