#!/command/with-contenv sh
# shellcheck shell=sh

CONFIG_ARG=""
if [ ! -z "${CONFIG_FILE}" ]; then
  CONFIG_ARG="--config ${CONFIG_FILE}"
fi

# Prevent reading the token from the forgejo-runner process
unset FORGEJO_REGISTRATION_TOKEN

cd /config
exec forgejo-runner daemon ${CONFIG_ARG}
