#!/command/with-contenv bash
# shellcheck shell=bash

# Enable Tini subreaping, because dind is running within s6
export TINI_SUBREAPER=1

exec s6-notifyoncheck -s 5000 -T 60000 -t 1000 -w 2000 -n 30 \
                      /usr/local/bin/dockerd-entrypoint.sh
