#!/usr/bin/env bash

s6-svwait -t 30000 -U /etc/s6/docker

CONFIG_ARG=""
if [[ ! -z "${CONFIG_FILE}" ]]; then
  CONFIG_ARG="--config ${CONFIG_FILE}"
fi

# Prevent reading the token from the forgejo-runner process
unset FORGEJO_REGISTRATION_TOKEN

cd /data
forgejo-runner daemon ${CONFIG_ARG}
