#!/command/with-contenv bash
# shellcheck shell=bash

CRON_LOG_LEVEL=$(case ${LOG_LEVEL} in \
        "debug") echo "0"          ;; \
        "info")  echo "4"          ;; \
        "warn")  echo "6"          ;; \
        "error") echo "7"          ;; \
        "fatal") echo "8"          ;; \
esac)

exec crond -f -l "${CRON_LOG_LEVEL}"
